# Generated by Django 5.1.6 on 2025-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_rate_alter_chatmessage_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='audio_file',
            field=models.FileField(default=10, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
